apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
spec:
  selector:
    matchLabels:
      app: shopping
  replicas: 3
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: shopping
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: NodePort
  selector:
    app: shopping
  ports:
    - nodePort: 30080
      port: 8081
      targetPort: 8080
